"""rbac: pn_perm_override + user last_login

Revision ID: 123355de3607
Revises: 35a844c6ece5
Create Date: 2026-09-05 10:48:35.326177
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '123355de3607'
down_revision: Union[str, None] = '35a844c6ece5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pn_perm_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('perm', sa.String(length=50), nullable=False, comment='权限点，如 users / orders:read'),
    sa.Column('effect', sa.String(length=8), nullable=False, comment='grant 授予 / deny 撤销'),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['pn_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'perm', name='uq_user_perm_override')
    )
    op.create_index(op.f('ix_pn_perm_override_user_id'), 'pn_perm_override', ['user_id'], unique=False)
    op.add_column('pn_user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('pn_user', sa.Column('last_login_ip', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pn_user', 'last_login_ip')
    op.drop_column('pn_user', 'last_login_at')
    op.drop_index(op.f('ix_pn_perm_override_user_id'), table_name='pn_perm_override')
    op.drop_table('pn_perm_override')
    # ### end Alembic commands ###
