"""init: pn_user, pn_order, pn_order_item, pn_sys_log

Revision ID: 35a844c6ece5
Revises: 
Create Date: 2026-09-04 23:45:57.843311
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '35a844c6ece5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pn_sys_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.String(length=16), server_default='INFO', nullable=False),
    sa.Column('source', sa.String(length=64), server_default='system', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pn_sys_log_user_id'), 'pn_sys_log', ['user_id'], unique=False)
    op.create_table('pn_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='wing', nullable=False),
    sa.Column('wx_openid', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('wx_openid')
    )
    op.create_index(op.f('ix_pn_user_username'), 'pn_user', ['username'], unique=True)
    op.create_table('pn_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'shipped', 'completed', 'cancelled', name='pn_order_status'), server_default='pending', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['pn_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pn_order_order_no'), 'pn_order', ['order_no'], unique=True)
    op.create_index(op.f('ix_pn_order_status'), 'pn_order', ['status'], unique=False)
    op.create_index(op.f('ix_pn_order_user_id'), 'pn_order', ['user_id'], unique=False)
    op.create_table('pn_order_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['pn_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pn_order_item_order_id'), 'pn_order_item', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pn_order_item_order_id'), table_name='pn_order_item')
    op.drop_table('pn_order_item')
    op.drop_index(op.f('ix_pn_order_user_id'), table_name='pn_order')
    op.drop_index(op.f('ix_pn_order_status'), table_name='pn_order')
    op.drop_index(op.f('ix_pn_order_order_no'), table_name='pn_order')
    op.drop_table('pn_order')
    op.drop_index(op.f('ix_pn_user_username'), table_name='pn_user')
    op.drop_table('pn_user')
    op.drop_index(op.f('ix_pn_sys_log_user_id'), table_name='pn_sys_log')
    op.drop_table('pn_sys_log')
    # ### end Alembic commands ###
